name = "Hugo Myblog Theme"
description = ""
homepage = "https://example.com/"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
tags = []
features = []
min_version = "0.65.0"

[author]
  name = ""
  homepage = ""

[original]
  name = "zzossig"
  homepage = "https://zzossig.io"
  repo = ""
