[[main]]
  identifier = "about"
  name = "A Propos"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "galleries"
  name = "Galeries"
  url = "galleries"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 5

[[main]]
  identifier = "search"
  name = "icon-search"
  url = "search"
  weight = 6